version: '3'
services:
  lap:
    image: fauria/lap:latest
    restart: always
    ports:
      - ${PORT_SPACE}80:80
    volumes:
      - lap:/var/www/html
  lap-demo:
    image: fauria/lap:latest
    restart: always
    ports:
      - ${PORT_SPACE}81:80
    volumes:
      - lap-demo:/var/www/html
  
  strapi:
    image: strapi/strapi
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_SSL: 'false'
    volumes:
      - strapi:/srv/app
    ports:
      - '${PORT_SPACE}37:1337'
    depends_on:
      - mysql

  mysql:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: strapi
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}


volumes:
  lap:
  lap-demo:
  mysql:
  strapi:
