version: '3'
services:
  nginx:
    image: ghcr.io/piitschy/silentparty-web/nginx:${RELEASE_TAG:-latest}
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.http.routers.${STACKNAME}-nuxt.rule=Host(`silentparty-hannover.de`)"
        - "traefik.http.routers.${STACKNAME}-nuxt.entrypoints=web,websecure"
        - "traefik.http.routers.${STACKNAME}-nuxt.tls=true"
        - "traefik.http.routers.${STACKNAME}-nuxt.tls.certresolver=letsencrypt"
        - "traefik.http.services.${STACKNAME}-nuxt.loadbalancer.server.port=80"

  nginx-demo:
    image: ghcr.io/piitschy/silentparty-web/nginx:${VERSION_TAG:-latest}
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.http.routers.${STACKNAME}-nuxt.rule=Host(`demo.silentparty-hannover.de`)"
        - "traefik.http.routers.${STACKNAME}-nuxt.entrypoints=web,websecure"
        - "traefik.http.routers.${STACKNAME}-nuxt.tls=true"
        - "traefik.http.routers.${STACKNAME}-nuxt.tls.certresolver=letsencrypt"
        - "traefik.http.services.${STACKNAME}-nuxt.loadbalancer.server.port=80"

networks:
  traefik-public:
    driver: overlay
    external: true
    attachable: true
