version: '3'
services:
  lap:
    image: fauria/lap:latest
    restart: always
    ports:
      - ${PORT_SPACE}80:80
    volumes:
      - lap:/var/www/html
  lap-demo:
    image: fauria/lap:latest
    restart: always
    ports:
      - ${PORT_SPACE}81:80
    volumes:
      - lap-demo:/var/www/html

volumes:
  lap:
  lap-demo:
