on:
  release:
    types: [published]

name: deploy on release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Set TAG
      run: |
        IMG=ghcr.io/${GITHUB_REPOSITORY@L}/nginx
        echo "IMG=$IMG" >> $GITHUB_ENV
        
    - uses: actions/checkout@v4

    - uses: GuillaumeFalourd/get-release-or-tag@v2
      id: tag

    - name: Log in to ghcr.io
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      
    - name: Build the Docker image
      run: docker build -t ${{ env.IMG }}:${{ steps.tag.outputs.tag }} -t ${{ env.IMG }}:latest .

    - name: Push image to GHCR
      run: docker push ${{ env.IMG }} --all-tags

    - name: Pull Webhook
      run: curl -X POST -k ${{vars.WEBHOOK}}?RELEASE_TAG=${{ steps.tag.outputs.tag }}
